[server]
host = "127.0.0.1"
port = 3000

[database]
url = "sqlite:trade_alert.db"

[logging]
level = "info"

[scheduler]
# Default cron schedule for checking alerts (every 5 minutes)
default_schedule = "*/5 * * * *"

[price_fetcher]
update_interval_secs = 1