[server]
host = "127.0.0.1"
port = 3000

[database]
url = "sqlite:trade_alert.db"

[logging]
level = "info"

[scheduler]
# Default cron schedule for checking alerts (every 5 minutes)
default_schedule = "*/5 * * * *"

[price_fetcher]
# 价格更新间隔（秒）
update_interval_secs = 30
# 缓存过期时间（秒）
cache_ttl_secs = 30
# 最大重试次数
max_retries = 3
# 并发请求限制
max_concurrent_requests = 5
# 每小时最大请求数
max_requests_per_hour = 2000
# 请求超时时间（秒）
request_timeout_secs = 10
# 连接池空闲超时时间（秒）
pool_idle_timeout_secs = 30

[email]
# SMTP服务器配置
smtp_server = "smtp.gmail.com"
smtp_port = 587
smtp_username = "your_email@gmail.com"
smtp_password = "your_app_password"
from_email = "your_email@gmail.com"
from_name = "交易预警系统"
# 接收预警的邮箱
to_email = "your_email@gmail.com"
# 是否启用邮件通知
enabled = true